/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_montycall_android_lebanoncall_MontyNative */

#ifndef _Included_com_montycall_android_lebanoncall_MontyNative
#define _Included_com_montycall_android_lebanoncall_MontyNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_montycall_android_lebanoncall_MontyNative
 * Method:    getPrivateKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_montycall_android_lebanoncall_MontyNative_getPrivateKey
  (JNIEnv *, jobject);

/*
 * Class:     com_montycall_android_lebanoncall_MontyNative
 * Method:    getTokenString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_montycall_android_lebanoncall_MontyNative_getTokenString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
